"""Compatibility exports for the default Workspace document/file-probe scenario."""

from denialdojo.scenarios.workspace_document_file_probe import (
    ATTACK_INJECTION,
    ATTACK_RECIPIENT,
    ATTACK_SUBJECT,
    BENIGN_BODY,
    BENIGN_FILE_NOTE,
    BENIGN_RECIPIENT,
    BENIGN_SUBJECT,
    REGISTERED_CODES,
    SCENARIO_ID,
    USER_TASK28_NORMALIZED_UTILITY_TARGET,
    WORKSPACE_INJECTION_KEY,
    WORKSPACE_SUITE,
    DenialWorkspaceEnvironment,
    DenialWorkspaceRuntime,
    WorkspaceBenignRecoveryTask,
    WorkspaceEnvironment,
    WorkspaceLeakageTask,
    WorkspaceScoreTask,
    build_workspace_environment,
    decode_attack_sink,
    injected_feedback_content,
    intervention_count,
    new_sent_messages,
    probe_restricted_file,
)

__all__ = [
    "ATTACK_INJECTION",
    "ATTACK_RECIPIENT",
    "ATTACK_SUBJECT",
    "BENIGN_BODY",
    "BENIGN_FILE_NOTE",
    "BENIGN_RECIPIENT",
    "BENIGN_SUBJECT",
    "REGISTERED_CODES",
    "SCENARIO_ID",
    "USER_TASK28_NORMALIZED_UTILITY_TARGET",
    "WORKSPACE_INJECTION_KEY",
    "WORKSPACE_SUITE",
    "DenialWorkspaceEnvironment",
    "DenialWorkspaceRuntime",
    "WorkspaceBenignRecoveryTask",
    "WorkspaceEnvironment",
    "WorkspaceLeakageTask",
    "WorkspaceScoreTask",
    "build_workspace_environment",
    "decode_attack_sink",
    "injected_feedback_content",
    "intervention_count",
    "new_sent_messages",
    "probe_restricted_file",
]
